services:
  
  llm_service_with_llama_cpp:
    image: ghcr.io/ggml-org/llama.cpp:full-cuda
    container_name: llm_service
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./llm_service/models:/models
      - ./llm_service/llama-cache:/root/.cache/llama.cpp
      - ./llm_service/app_scripts:/app_scripts

      # === change for yout model path ===
      - ../agents/cache_models:/cache_models
    environment:
      - CUDA_VISIBLE_DEVICES=0
    runtime: nvidia
    tty: true
    stdin_open: true
    entrypoint: ["sleep", "infinity"]

  vector_store_service:
    image: qdrant/qdrant:latest
    container_name: vectore_store_services
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./vector_store/qdrant_storage:/qdrant/storage
      - ./vector_store/qdrant_snapshots:/qdrant/snapshots
    environment:
      - QDRANT__SERVICE__API_KEY=${QDRANT_SERVICE_API_KEY}

  embedding_service:
    build: ./embedding_service
    container_name: embedding_service
    ports:
      - "8003:8000"
    volumes:
      - ./embedding_service:/app
    restart: unless-stopped
    runtime: nvidia 
    environment:
      - CUDA_VISIBLE_DEVICES=0
